In [1]:
import pandas as pd

import numpy as np

In [2]:
data=pd.read_excel("Donnees_Stagiaire_Marcellin.xls")

ImportError: `Import xlrd` failed. Install xlrd >= 2.0.1 for xls Excel support Use pip or conda to install the xlrd package.

In [ ]:
data.head()

,Name,Geogr1,Geogr2,Year,Eg el abbreviation,Name.1,Description,Month,Time,01,...,22,23,24,25,26,27,28,29,30,31
0,KANDI_AEROPORT,2.9333,11.1333,2015,PSTAD,Pression Station Moy,hPa,1,06:00,979.9,...,979.6,978.7,977.0,976.4,977.9,978.3,978.1,977.9,978.3,978.3
1,KANDI_AEROPORT,2.9333,11.1333,2015,PSTAD,Pression Station Moy,hPa,2,06:00,977.7,...,977.4,979.5,979.2,976.8,976.5,978.2,978.4,NaN,NaN,NaN
2,KANDI_AEROPORT,2.9333,11.1333,2015,PSTAD,Pression Station Moy,hPa,3,06:00,978.6,...,974.8,974.3,974.1,975.4,977.9,978.5,978.1,976.5,976.2,977.1
3,KANDI_AEROPORT,2.9333,11.1333,2015,PSTAD,Pression Station Moy,hPa,4,06:00,978.5,...,975.9,975.9,975.9,977.5,977.2,977.1,976.2,976.0,974.7,NaN
4,KANDI_AEROPORT,2.9333,11.1333,2015,PSTAD,Pression Station Moy,hPa,5,06:00,973.9,...,977.8,976.9,977.9,977.0,975.7,976.2,976.6,975.5,976.4,976.2

In [ ]:
data.Name.unique()

array(['KANDI_AEROPORT', 'PARAKOU_AEROPORT'], dtype=object)

In [ ]:
data.columns

Index(['Name', 'Geogr1', 'Geogr2', 'Year', 'Eg el abbreviation', 'Name.1',
       'Description', 'Month', 'Time', '01', '02', '03', '04', '05', '06',
       '07', '08', '09', '10', '11', '12', '13', '14', '15', '16', '17', '18',
       '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '30',
       '31'],
      dtype='object')

In [ ]:
annee=pd.date_range(start='2015-01-01',end='2025-12-31',freq='D')

annee

DatetimeIndex(['2015-01-01', '2015-01-02', '2015-01-03', '2015-01-04',
               '2015-01-05', '2015-01-06', '2015-01-07', '2015-01-08',
               '2015-01-09', '2015-01-10',
               ...
               '2025-12-22', '2025-12-23', '2025-12-24', '2025-12-25',
               '2025-12-26', '2025-12-27', '2025-12-28', '2025-12-29',
               '2025-12-30', '2025-12-31'],
              dtype='datetime64[ns]', length=4018, freq='D')

In [ ]:
annee.year

Index([2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015,
       ...
       2025, 2025, 2025, 2025, 2025, 2025, 2025, 2025, 2025, 2025],
      dtype='int32', length=4018)

In [ ]:
data_Kandi=pd.DataFrame({"Lieu":"KANDI_AEROPORT","annee":annee.year,"mois":annee.month,"jour":annee.day})

data_parakou=pd.DataFrame({"Lieu":"PARAKOU_AEROPORT","annee":annee.year,"mois":annee.month,"jour":annee.day})

In [ ]:
data_Kandi.head()

             Lieu  annee  mois  jour
0  KANDI_AEROPORT   2015     1     1
1  KANDI_AEROPORT   2015     1     2
2  KANDI_AEROPORT   2015     1     3
3  KANDI_AEROPORT   2015     1     4
4  KANDI_AEROPORT   2015     1     5

In [ ]:
data_parakou.head()

               Lieu  annee  mois  jour
0  PARAKOU_AEROPORT   2015     1     1
1  PARAKOU_AEROPORT   2015     1     2
2  PARAKOU_AEROPORT   2015     1     3
3  PARAKOU_AEROPORT   2015     1     4
4  PARAKOU_AEROPORT   2015     1     5

In [ ]:
data=data.rename(columns={"01":"1","02":"2","03":"3","04":"4","05":"5","06":"6","07":"7","08":"8","09":"9"})

In [ ]:
data.Description.unique()

array(['hPa', 'mm', '°C', '%', 'm/s'], dtype=object)

In [ ]:
def verif(data_verif):
    if 0<len(data_verif):
        return data_verif.iloc[0]
    else:
        return np.nan
def verif_temp(data_verif_temp):
    if 2<=len(data_verif_temp):
        return [data_verif_temp.iloc[0],data_verif_temp.iloc[1]]
    elif len(data_verif_temp)==1:
        return [data_verif_temp.iloc[0],data_verif_temp.iloc[0]]
    else:
        return[np.nan,np.nan]
    
def creation(data_ge,lieu):
    list_pression=[]
    list_pluvimetrie=[]
    list_temperature_max=[]
    list_temperature_min=[]
    list_humidite=[]
    list_vitesse_vent=[]

    data_gene=data_ge.copy()
    for i in data_gene.index:
        Annee=data_gene.iloc[i]["annee"]
        Mois=data_gene.iloc[i]["mois"]
        Jour=data_gene.iloc[i]["jour"]
    
        data_virt=data[(data.Name==lieu) & (data.Year==Annee) & (data.Month==Mois)]

        list_pression.append(verif(data_virt[data_virt.Description=="hPa"][f"{Jour}"]))

        list_temperature_max.append(verif_temp(data_virt[data_virt.Description=='°C'][f"{Jour}"])[0])

        list_temperature_min.append(verif_temp(data_virt[data_virt.Description=='°C'][f"{Jour}"])[1])
                                
        list_humidite.append(verif(data_virt[data_virt.Description=='%'][f"{Jour}"]))

        list_vitesse_vent.append(verif(data_virt[data_virt.Description=='m/s'][f"{Jour}"]))

        list_pluvimetrie.append(verif(data_virt[data_virt.Description=="mm"][f"{Jour}"]))

    data_gene["Pression"]=list_pression

    data_gene["Temperature_Max"]=list_temperature_max

    data_gene["Temperature_Min"]=list_temperature_min

    data_gene["Humidite"]=list_humidite

    data_gene["Vitesse_Vent"]=list_vitesse_vent

    data_gene["Pluviometrie"]=list_pluvimetrie

    return data_gene

In [ ]:
data_Kandi=creation(data_Kandi,"KANDI_AEROPORT")

data_parakou=creation(data_parakou,"PARAKOU_AEROPORT")

In [ ]:
data_Kandi

,Lieu,annee,mois,jour,Pression,Temperature_Max,Temperature_Min,Humidite,Vitesse_Vent,Pluviometrie
0,KANDI_AEROPORT,2015,1,1,979.9,32.0,13.4,32.0,2.4,0.0
1,KANDI_AEROPORT,2015,1,2,981.4,30.3,17.4,26.0,2.3,0.0
2,KANDI_AEROPORT,2015,1,3,982.8,29.2,17.7,20.0,3.5,0.0
3,KANDI_AEROPORT,2015,1,4,983.8,29.0,15.8,20.0,2.8,0.0
4,KANDI_AEROPORT,2015,1,5,982.7,29.5,13.5,29.0,3.0,0.0
...,...,...,...,...,...,...,...,...,...,...
4013,KANDI_AEROPORT,2025,12,27,976.9,37.4,20.4,28.0,1.4,0.0
4014,KANDI_AEROPORT,2025,12,28,977.5,36.9,19.7,27.0,2.0,0.0
4015,KANDI_AEROPORT,2025,12,29,978.2,37.5,19.8,31.0,1.5,0.0
4016,KANDI_AEROPORT,2025,12,30,978.9,37.7,20.0,32.0,1.9,0.0
4017,KANDI_AEROPORT,2025,12,31,978.4,37.3,19.7,30.0,2.1,0.0

In [ ]:
data_parakou

,Lieu,annee,mois,jour,Pression,Temperature_Max,Temperature_Min,Humidite,Vitesse_Vent,Pluviometrie
0,PARAKOU_AEROPORT,2015,1,1,967.5,34.6,19.2,23.0,3.6,0.0
1,PARAKOU_AEROPORT,2015,1,2,968.6,32.6,18.5,24.0,4.3,0.0
2,PARAKOU_AEROPORT,2015,1,3,969.9,32.5,18.9,20.0,4.9,0.0
3,PARAKOU_AEROPORT,2015,1,4,970.8,32.5,16.5,23.0,5.0,0.0
4,PARAKOU_AEROPORT,2015,1,5,969.9,31.9,15.9,23.0,5.1,0.0
...,...,...,...,...,...,...,...,...,...,...
4013,PARAKOU_AEROPORT,2025,12,27,966.0,36.0,22.3,61.0,1.6,0.0
4014,PARAKOU_AEROPORT,2025,12,28,966.3,37.2,22.2,56.0,2.3,0.0
4015,PARAKOU_AEROPORT,2025,12,29,967.2,36.0,21.2,64.0,2.1,0.0
4016,PARAKOU_AEROPORT,2025,12,30,968.0,36.3,22.7,65.0,2.3,0.0
4017,PARAKOU_AEROPORT,2025,12,31,967.2,37.2,23.1,55.0,2.4,0.0

In [ ]:
data_Kandi.to_csv("data/KANDI.csv",index=False)
data_parakou.to_csv("data/PARAKOU.csv",index=False)